# Generated by Django 3.0.8 on 2020-08-29 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
