# Generated by Django 3.0.8 on 2020-09-02 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200901_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 7, 47, 40, 869749, tzinfo=utc)),
        ),
    ]
